[package]
name = "nin"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]

[target.'cfg(not(target_os = "android"))'.dependencies]
eframe = { version = "0.36", default-features = false, features = [
    "default_fonts",
    "wayland",
    "wgpu",
] }

[target.'cfg(target_os = "android")'.dependencies]
eframe = { version = "0.36", default-features = false, features = [
    "default_fonts",
    "android-native-activity",
    "glow",
] }
